// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"basic-rest-api-orm/api/handler"
	"basic-rest-api-orm/initializer"
	"basic-rest-api-orm/repository"
	"basic-rest-api-orm/service/author"
	"github.com/go-pg/pg/v10"
)

// Injectors from wire.go:

func InitApi(db *pg.DB) initializer.Provider {
	authorRepository := repository.ProvideAuthorRepository(db)
	authorService := authorservice.ProvideAuthorService(authorRepository)
	authorHandler := handler.ProviderAuthorHandler(authorService)
	todoHandler := handler.ProviderTodoHandler()
	provider := initializer.InitProvider(authorHandler, todoHandler)
	return provider
}
